/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProyectoRouteImport } from './routes/proyecto'
import { Route as MaterialesRouteImport } from './routes/materiales'
import { Route as FuncionesRouteImport } from './routes/funciones'
import { Route as EnsayosRouteImport } from './routes/ensayos'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as ArticulosRouteImport } from './routes/articulos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FuncionesSlugRouteImport } from './routes/funciones_.$slug'

const ProyectoRoute = ProyectoRouteImport.update({
  id: '/proyecto',
  path: '/proyecto',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialesRoute = MaterialesRouteImport.update({
  id: '/materiales',
  path: '/materiales',
  getParentRoute: () => rootRouteImport,
} as any)
const FuncionesRoute = FuncionesRouteImport.update({
  id: '/funciones',
  path: '/funciones',
  getParentRoute: () => rootRouteImport,
} as any)
const EnsayosRoute = EnsayosRouteImport.update({
  id: '/ensayos',
  path: '/ensayos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticulosRoute = ArticulosRouteImport.update({
  id: '/articulos',
  path: '/articulos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FuncionesSlugRoute = FuncionesSlugRouteImport.update({
  id: '/funciones_/$slug',
  path: '/funciones/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/articulos': typeof ArticulosRoute
  '/contacto': typeof ContactoRoute
  '/ensayos': typeof EnsayosRoute
  '/funciones': typeof FuncionesRoute
  '/materiales': typeof MaterialesRoute
  '/proyecto': typeof ProyectoRoute
  '/funciones/$slug': typeof FuncionesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/articulos': typeof ArticulosRoute
  '/contacto': typeof ContactoRoute
  '/ensayos': typeof EnsayosRoute
  '/funciones': typeof FuncionesRoute
  '/materiales': typeof MaterialesRoute
  '/proyecto': typeof ProyectoRoute
  '/funciones/$slug': typeof FuncionesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/articulos': typeof ArticulosRoute
  '/contacto': typeof ContactoRoute
  '/ensayos': typeof EnsayosRoute
  '/funciones': typeof FuncionesRoute
  '/materiales': typeof MaterialesRoute
  '/proyecto': typeof ProyectoRoute
  '/funciones_/$slug': typeof FuncionesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/articulos'
    | '/contacto'
    | '/ensayos'
    | '/funciones'
    | '/materiales'
    | '/proyecto'
    | '/funciones/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/articulos'
    | '/contacto'
    | '/ensayos'
    | '/funciones'
    | '/materiales'
    | '/proyecto'
    | '/funciones/$slug'
  id:
    | '__root__'
    | '/'
    | '/articulos'
    | '/contacto'
    | '/ensayos'
    | '/funciones'
    | '/materiales'
    | '/proyecto'
    | '/funciones_/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArticulosRoute: typeof ArticulosRoute
  ContactoRoute: typeof ContactoRoute
  EnsayosRoute: typeof EnsayosRoute
  FuncionesRoute: typeof FuncionesRoute
  MaterialesRoute: typeof MaterialesRoute
  ProyectoRoute: typeof ProyectoRoute
  FuncionesSlugRoute: typeof FuncionesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/proyecto': {
      id: '/proyecto'
      path: '/proyecto'
      fullPath: '/proyecto'
      preLoaderRoute: typeof ProyectoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materiales': {
      id: '/materiales'
      path: '/materiales'
      fullPath: '/materiales'
      preLoaderRoute: typeof MaterialesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funciones': {
      id: '/funciones'
      path: '/funciones'
      fullPath: '/funciones'
      preLoaderRoute: typeof FuncionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ensayos': {
      id: '/ensayos'
      path: '/ensayos'
      fullPath: '/ensayos'
      preLoaderRoute: typeof EnsayosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articulos': {
      id: '/articulos'
      path: '/articulos'
      fullPath: '/articulos'
      preLoaderRoute: typeof ArticulosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funciones_/$slug': {
      id: '/funciones_/$slug'
      path: '/funciones/$slug'
      fullPath: '/funciones/$slug'
      preLoaderRoute: typeof FuncionesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArticulosRoute: ArticulosRoute,
  ContactoRoute: ContactoRoute,
  EnsayosRoute: EnsayosRoute,
  FuncionesRoute: FuncionesRoute,
  MaterialesRoute: MaterialesRoute,
  ProyectoRoute: ProyectoRoute,
  FuncionesSlugRoute: FuncionesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
